@startuml activity

skinparam defaultTextAlignment center
skinparam defaultFontSize 10
skinparam wrapWidth 300

start

group Обработка модификации (Modification)\nили ее возможности (Feature) {

    if (Модификация или возможность включены пользователем?) then (Да)
        if (Присутствует ключ @patches?) then (Да)
            :Прочитать список файлов из @patches;

            while (Остались необработанные файлы в списке?) is (Да)
                :Прочитать файл по относительному пути;
                :Загрузить его как JSON-объект TablePatches;
                #dedefe :Применить патчи из этого объекта TablePatches;
            endwhile (Нет)
        else (Нет)
            :Составить объект TablePatches из ключей текущего объекта, которые не начинаются с @;
            #dedefe :Применить патчи из этого объекта TablePatches;
        endif
        if (Присутствует ключ @root?) then (Да)
            :Прочитать относительный путь из @root;
            #defede :Предоставить игре все файлы из каталога по указанному пути;
        else (Нет)
            if (Тип текущего объекта?) then (Modification)
                #defede :Предоставить игре все файлы из корня модификации;
            else (Feature)
                :Проверить каталог в корне модификации, название которого будет совпадать с ID возможности;
                if (Каталог существует?) then (Да)
                    #defede :Предоставить игре все файлы из этого каталога;
                else (Нет)
                endif
            endif
        endif
    else (Нет)
    endif

}

stop


@enduml